services:
  db:
    image: postgres:15.1-alpine
    container_name: 'choizy-bot'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-choizy:/var/lib/postgresql/data

volumes:
  postgres-choizy: